services:
  - type: web
    name: jobboard
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///jobboard.db
      - key: ADZUNA_APP_ID
        value: 5de5be17
      - key: ADZUNA_API_KEY
        value: 0e13ae3817f5dd76f691dfb5728b0499
